services:
  workaholic.categoryservice.api:
    image: workaholic.categoryservice.api
    build:
      context: .
      dockerfile: Workaholic.CategoryService.Api/Dockerfile
    depends_on: 
      - mongo
    ports:
      - "1454:80"
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
